apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-packet-loss
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: ai-smartlite
  loss:
    loss: '25'
    correlation: '25'
  duration: '30s'
  scheduler:
    cron: '@every 2h'
